---
name: release

on:
  push:
    branches:
      - master
      - 0.19.1
  pull_request:

jobs:
  docker-compose-build:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    permissions:
      packages: write
    if: github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - run: echo "TAG_NAME=${HEAD_REF//\//-}" >> "$GITHUB_ENV"
        env:
          HEAD_REF: ${{github.head_ref}}
        if: ${{ github.event_name == 'pull_request' }}
      - run: echo 'TAG_NAME=latest' >> "$GITHUB_ENV"
        if: ${{ github.event_name == 'push' }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: installers/linux/Dockerfile
          tags: ghcr.io/dev-hato/compiler:${{env.TAG_NAME}}
          platforms: |
            linux/amd64
            linux/arm64
